name: DAST - OWASP ZAP

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'   # ajuste se seu projeto for .NET 7/6

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

  zap-scan:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

            - name: Set target URL
        run: echo "ZAP_TARGET_URL=${{ secrets.ZAP_TARGET_URL }}" >> $GITHUB_ENV

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: ${{ env.ZAP_TARGET_URL }}
          cmd_options: >
            -r zap-report.html
            -x zap-report.xml
            -J zap-report.json
            -a               # ativa modo 'aggressive' light (sem full active scan)
            -m 10            # max 10 minutos (ajuste se quiser mais)
            -w zap-warn.txt  # arquivo com alertas
          allow_issue_writing: false

      - name: Upload ZAP report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            zap-report.html
            zap-report.xml
            zap-report.json
            zap-warn.txt

      # Opcional: falhar pipeline se tiver achados de alta severidade
      - name: Fail on High Risk Alerts
        run: |
          if grep -qi "High" zap-warn.txt; then
            echo "High risk alerts found by ZAP"
            exit 1
          fi
